version: '3.8'
services:
  movies:
    image: kastrov/netflix-movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: kastrov/netflix-webseries:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: kastrov/netflix-documentaries:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: kastrov/netflix-animations:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
